### ISSUE TITLE
simple creation of data-processing modules S-D7

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#1070]
service to support the creation of data analysis modules (e.g., out of a matlab/bash/python/R script; through dedicated webGUI) to make them shareable and useable as part of pipelined workflows making this user-friendly is to get SPARC researchers to put their analysis scripts on the platform and share them. It is key to the new focus on broadening the platform from simulations to general computational studies. SIM-CORE will reach out to SPARC teams in advance to identify existing data analysis functionality and requirements, and later to encourage onboarding. published analysis modules shall be visible in the o2S2PARC service catalogue, and shall also be found on a dedicated page on the Portal
- [ ] the SIM-CORE application and support team has reached out to SPARC teams to identify/ gather feedback about the existing and required data analysis and visualization functionalities
- [ ] a webGUI exists that allows a user to easily turn a data analysis script (matlab/bash/python/R) into a pipeline-able service that is accessible and shareable through o2S2PARC
- [ ] published analysis modules are visible in the o2S2PARC service catalogue, and can also be found on a dedicated page on the Portal
- [ ] the SIM-CORE application and support team reaches out to SPARC teams to encourage and support onboarding of data-analysis functionality

**Comment by pcrespov** [comment]
This is duplicated of ITISFoundation/osparc-issues#21
