### ISSUE TITLE
update osparc-simcore to python 3.7 or even 3.8

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1412]
As pika, psycopg was updated, there is nothing preventing from updating

- [x] upgrade all dependencies, specially limiting ones
   - start with packages
   - then services ( for services, first upgrade dockerfiles)
- [x] upgrade docker base images
- [x] automate upgrade process
    - upgrade reqs workflow?
    - sync between host venv, tooling venv and docker env?
- [x] setup compatibility matrix (e.g. tox) to monitor issues with future 3.x upgrades? 
- [ ] set pyenv??
