### ISSUE TITLE
Issues detected in Monitoring stack

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1847]
After detecting some failures, we decided to gather some of the issues we have detected under this case. It can later also be used as epic.

- [ ] storage scrapping takes several seconds while the others ms (might be due to monitoring healthcheck entrypoint is not filtered out)
- [ ] All data produced by monitoring simcore services using Prometheus client are discontinues and seem lost
    - are discontinues
    - service restarts makes reset counters to zero
    - all data missing later than the data produced by other exporters (e.g. node or cadvisor)
- [ ] report generator (pdf) failed
- [ ] ...

**Comment by sanderegg** [comment]
After some research:
- discontinuities in counters are expected by prometheus and should be handled when one does queries using operators such as ```rate()```, ```increase()```, etc... see for example [here](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate)
- concerning missing data before 28.09 @Surfict is double-checking if something went wrong when migrating from the old AWS IT to the new one
- the PDF reporter was failing since some of the metrics take too much memory to compute (also visible in the dashboards when setting a long time) - this can be aleviated by using prometheus recording rules some times and some times it is just not the right tool for generating KPIs (for example generating a increase over 3month is equal to recovering the time series over all that time and computing one value out of that which can be massive, especially if the values are summed as well over different labels)

**Comment by sanderegg** [comment]
obsolete
