### ISSUE TITLE
Review webserver API

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1976]
Add issues we find in the webserver API and later can be append as subcases:

- [ ] web OAS should use camelcase: see [here](https://github.com/ITISFoundation/osparc-simcore/pull/1941#discussion_r526206062)
- [ ] validation should be done via pydantic. Remove openapi-core
- [ ] add  in/out API models and in/out DB models. Avoid over-validation use light constructs when data was verified
- [ ] .env and docker-compose environemtns?
- [ ] create aioresponse from directorv2 to test directorv2 client in different situations e.g. error, delays, etc

**Comment by sanderegg** [comment]
shall we close this @pcrespov ? this is pretty old and water flew under the bridge

**Comment by pcrespov** [comment]
Yes, this is obsolete
