### ISSUE TITLE
Move current deprecated director to director-v2 and retire

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1988]
```[tasklist]
### Tasks
- [ ] The catalog service shall handle everything related to the docker registry
- [ ] The handling of the dynamic services shall be handled by the director-v2
- [ ] remove any occurence of director-v0 in the other services but director-v2
- [ ] move the legacy services in the director-v2
- [ ] move the registry in catalog
- [ ] remove completely the director-v0
```

**Comment by sanderegg** [comment]
- The catalog service shall handle everything related to the docker regitry
- The handling of the dynamic services shall be handled by the director-v2
Then remove the director-v0

**Comment by sanderegg** [comment]
waiting for dynamic services to be ported

**Comment by pcrespov** [comment]
IMPORTANT: for point 3 there is some code already [in place in ITISFoundation/osparc-simcore/packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker_registry.py](https://github.com/ITISFoundation/osparc-simcore/blob/d47be0e95f7701b06b46553c6881dbc03a75759f/packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker_registry.py#L28-L32) that can be reused
```py
class Registry:
    # SEE https://docs.docker.com/registry/spec/api
    # SEE  https://github.com/moby/moby/issues/9015

    def __init__(self, **data):
```
