### ISSUE TITLE
public API backlog

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2344]
Random list of enhancements

#### features
- [x]  hide api projects in UI 
- [ ] get logs
- [ ] get progress
- [ ] Limit resources: expiration date on files, projects, tasks -> deletes items in db and s3  after expiration
- [ ] Limit resources: calls/resources per user 
- [ ] Security: change auth scheme
- [ ] Security: hash tokens 

#### client
- [x] control template (add patches) 
- [ ] try new gpy teemplate oand the one with pydantic

#### dev refactor & testing
- [ ] robust error handling
- [ ] API performance test
- [ ] filter/pagination 
- [ ] move functionality to catalog
- [ ] move functionality to webserver
- [ ] move functionality to storage

**Comment by pcrespov** [comment]
outdated.
