### ISSUE TITLE
storage refactoring backlog

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2396]
Work on refactoring storage service

- [x] TIMEOUTS when opening templates ( PR #2301)
- [x] deprecate ``s3wrapper`` ( PR #2295 )
- [x] standard test/fixtures layout (PR #2276)
- [x] upgrade  services dependences as in [requires.io](https://requires.io/github/ITISFoundation/osparc-simcore/requirements/?branch=master) (PR #2276)
- [x] resolve ``urllib3`` constraint due to aioboto! (PR #2276)
- [x] remove limitation with aiobotocore dependency since it has breaking changes (PR #2276)
- [x] integration of new datcore/[pennsieve](https://github.com/Pennsieve/pennsieve-python) as a separate service (PR #2391)
- ~~[ ] deprecate ``storage_sdk``? ?  -> Only used in ``node-ports``. Basically node-ports is an sdk on top of storage and the pg db. The latter should be avoided.~~
- [x] handlers, routings and validation
- [x] ``files`` resource
- [x] lazy synchro between file_meta_data table and S3 backend
 - [ ] mark data as deleted. 
 - [ ] delayed copy of data (using links to source)
 - [x] delete file_meta_data entries that are older than the presigned links lifetime (currently 3days)
 - [x] adds entrypoint to get folder size/dates

Design towards:
- new file api
- access layer
- s3, samba-like, etc

#### guidon discussion on Oct27
- storage to upload/download from outside via pre-signed links
- storage to keep credentials for different mount types (e.g. ``filesrv`` gets mounted in a dy-sidecar will require user credentials) . have some doubts about this one
- storage provides a fuse-compatible interface that translates content of s3 into a file-system for a user including access-rights, etc. This might allow us to connect a fuse client to osparc-storage API and create a dropbox-like application in a desktop that replicates a piece of osparc storage in your own desktop.

**Comment by sanderegg** [comment]
storage refactoring was completed and new entries shall be created for further developments. thus closing this one now.
