### ISSUE TITLE
Retire deprecated director v0 service

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2599]
Remove all functionality of director service into director-v2 and catalog

- [ ] 1. remove any occurence of director-v0 in the other services but director-v2
- [ ] 2. move the legacy services in the director-v2
- [ ] 3. move the registry in catalog
- [ ] 4. remove completely the director-v0

**Comment by pcrespov** [comment]
IMPORTANT: for point 3 there is some code already [in place in ITISFoundation/osparc-simcore/packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker_registry.py](https://github.com/ITISFoundation/osparc-simcore/blob/d47be0e95f7701b06b46553c6881dbc03a75759f/packages/pytest-simcore/src/pytest_simcore/helpers/utils_docker_registry.py#L28-L32) that can be reused
```py
class Registry:
    # SEE https://docs.docker.com/registry/spec/api
    # SEE  https://github.com/moby/moby/issues/9015

    def __init__(self, **data):
```

**Comment by pcrespov** [comment]
Duplicated in https://github.com/ITISFoundation/osparc-simcore/issues/1988
