### ISSUE TITLE
Provide an "easy" way to connect backend service to frontend notification systems

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#3541]
The idea is to leverage our RabbitMQ messaging system to this end.

First a update/refactoring step is necessary:
- https://github.com/ITISFoundation/osparc-simcore/pull/3496
- https://github.com/ITISFoundation/osparc-simcore/pull/3492
- https://github.com/ITISFoundation/osparc-simcore/pull/3502

Next is to use the common rabbitmq client to send messages from:
- [x] autoscaling application to provide user feedback about cluster scaling
- [x] dynamic-sidecar powered services to provide user feedback on services states, pull/push progress
- [x] allow for disconnecting users for maintenance purpose

**Comment by sanderegg** [comment]
all the points were completed
