### ISSUE TITLE
Pass deployment variables to service containers

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#3565]
## USER STORY

1. Some services require environment variables that are set on a deployment level. If so, these variables will be referenced on the **image labels** and initialized to something reasonable. These variables must be passed to both, computational and dynamic services.
2. Environment variables on the deployment can define/override certain behavior on services upon **creation**.

## User case 1: Image Labels
- license servers, e.g. 27000@license.sim4life.com
  - sim4life
  - sim4life-lite
  - 3rd-party software
  - iSolve comp. service
- STUN/TURN servers, e.g. turn.sim4life.com
- Location of VIP models for sim4life
- Auto-save timeout for sim4life-lite
- location of data (e.g. for storing TI databases)

## Use case 2: Creation
- Remove all elevated privileges unless the deployment defines that otherwise (e.g. `cap_sys` for debugging in vivo)

## Use case 3: @colinRawlings 
Taken from https://github.com/ITISFoundation/osparc-simcore/pull/3921#issuecomment-1525083046

This would be very helpful for crash reporting in `s4l:web`.  In this use case we have a set of services:
- `s4l-core` (the backend)
- `rt-web` (the frontend)
- `sym-server` (the symbol server)

The `sym-server` holds the "sensitive" (in the sense that it indirectly exposes the source code) symbol database.  When a crash occurs `s4l-core`'s `monitor` application `POST` the binary `.dmp` file for analysis using the symbol database.  Following analysis the callstack and metadata should be placed in an AWS SQS queue for later ingestion by the gitlab issue tracker.  The `sym-server` obtains the details for the AWS queue from (3) environment variables.

### As a (developer-)user I would like:
- A way to inject the "secret" environment variables for the queue into the service (this seems consistent with the `vendor oenvs`).  This would avoid me having to add them in the code and allow me to replace all of them everywhere if a set of credentials was comprimised without changing the code or deployed version.

- A way to learn to augment the meta-data for each crash with the user info, platform info, ... (this seems consistent with the `session oenvs`)
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/3803
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/3921
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/3843
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4443
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4429
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4805
```

**Comment by GitHK** [comment]
Additional information:
- due to current request to block access to outgoing domains, we need a way to whitelist the content of the env vars for this services. Envoy proxy might be a solution for forwarding requests to DNS domains.

**Comment by pcrespov** [comment]
NOTES: 
 - SEE         https://git.speag.com/oSparc/osparc-s4l/-/blob/master/s4l-core/docker-compose-meta.yml#L29

**Comment by mguidon** [comment]
@pcrespov One more thing. It would be very useful to pass the information about whether the user is a tester or not (e.g. `TESTER_MODE_ENABLED=1`. That would allow me to enable/disable some settings only for testers, such as advanced video codec  settings.

**Comment by pcrespov** [comment]
## (⚠️ devops)
- Revert temporary changes done in staging until this PR is in https://github.com/ITISFoundation/osparc-simcore/pull/3921

**Comment by pcrespov** [comment]
SEE example in https://git.speag.com/oSparc/osparc-s4l/-/issues/609
