### ISSUE TITLE
Refactor osparc stack env-var handling

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3635]
- [x] @pcrespov : Dump currently used env-vars for local oSparc [list of unset & total list] . 
     - json-schemas of all service settings are produced as artifacts `system-test-swarm-deploy_services_settings_schemas.zip` on every build. SEE [gh-actions in master](https://github.com/ITISFoundation/osparc-simcore/actions?query=branch%3Amaster).
- [x]  ~~@mrnicegyu11: Add `osparc.local` full variable configuration (including what is now known as optional / default values) for *all* deployments. `repo.config` of a deployment *overwrites* the (`osparc.local`) defaults.~~
- [x]  @pcrespov : Change: All oSparc services fail if variables are unset
    -  service fails to start if faulty config
    -  adds a warning if settings field defaults to `null` (prevents situations in which typos in env-vars lead to null plugin settings that lead to shutting down plugins)
- [x]  @mrnicegyu11 Remove `env_file:     - ../.env` from `services/docker-compose.yml` in osparc-simcore and capture every single necessary env-var in the `environment:` section

```[tasklist]
### Tasks
- [ ] #3703
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3924
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/268
```

**Comment by pcrespov** [comment]
@mrnicegyu11 , my part is in principle done here. Let me know if you need extra from me.

**Comment by mrnicegyu11** [comment]
thanks a lot

**Comment by mrnicegyu11** [comment]
See https://github.com/ITISFoundation/osparc-ops-environments/issues/177

**Comment by pcrespov** [comment]
![Image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/4b9d066f-89d8-448d-a580-cf8f58768d6e)



![Image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/7d832a89-d3ba-4c33-9d36-3806563a6ee9)

**Comment by GitHK** [comment]
I have some questions as a developer. When dealing with env vars, I usually end up with in the following situations.

1. I define and env var in the settings of a service for `internal usage`. Does not require OPS value. I'd say that I will not expose/define it somewhere else. We have lots of these already
2. I define an env var in the settings of a service and it is mandatory. This means that it requires a value from OPS.
    - `Q1` where do I define it exacly?
    - `Q2` where do I put my default for development? 
3. I define an env var in the settings of a service but it has a default in the code.
    - `Q3` in theory I don't have to do anything else, do I still have to define it?
    - `Q4` where do I put my default for development?
    
@pcrespov @sanderegg @YuryHrytsuk @mrnicegyu11 @matusdrobuliak66 thanks for you help in clearing this up.

**Comment by mrnicegyu11** [comment]
re 1: ideally, no env-var should have defaults. So, to do it properly in this scenario, you should always NOT allow defaults and actually set the desired value as (what you call) "OPS value", always, even if it is considered `internal usage`.
re 2: This is the normal case. You put it in according to the docs made by @YuryHrytsuk . Your development default for now goes in the `.env-devel` of osparc-simcore
re 3: This should never happen, default values are not good practice.


@YuryHrytsuk please comment what I missed :--)

**Comment by sanderegg** [comment]
@GitHK 
My understanding:
1. not sure what is the point of having ENV variables for internal usage. what does this mean? why not just create some constant in the code then?
2.
 
  1. you need to define it in the osparc-simcore/services/docker-compose.yml file (such as MY_VAR=${MY_VAR})
  2. you need to define it in .env-devel so that developers can work, and that osparc-simcore is **self-consistent**
  3. you need to define that value in gitlab osparc-ops-environment-configuration (or whatever its name becomes @mrnicegyu11 @YuryHrytsuk ), in all the subfolders for all the deployments

3.  see 2. even if you define a default, please define it otherwise

**Comment by mrnicegyu11** [comment]
This is done
