### ISSUE TITLE
Creation of invitations

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3683]
How to generate invitations? Review web-based license requests for s4l 

- [x] check desktop workflow with app-team @eofli 
- [x] check desktop workflow with oetikers
- [x] design bridge service to provide invitations for different products to oetiker's system 
   - [x] implementation of the service #3710
   - [x] implemenation webserver's invitation plugin: #3767
   - [x] oetikers requested a change in the server: #3787
   - [x] follow up [issue](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/395) in osparc-ops to connect service to ``invitations.*`` DNS + activate ``auth`` @Surfict 
- [ ] iterate w/ app-team @eofli and oetikers
    - Tue Jan17

**Comment by pcrespov** [comment]
![image](https://user-images.githubusercontent.com/32402063/211770691-8f11b3c9-7056-48e5-a006-16c8d71842d4.png)

**Comment by pcrespov** [comment]
![image](https://user-images.githubusercontent.com/32402063/211770803-9101f6eb-65a8-45df-9de6-bc1fc627f6f8.png)

**Comment by pcrespov** [comment]
Reached production. ``INVITATIONS_HOST`` missing but @Surfict will add it ops
