### ISSUE TITLE
product-specific groups

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3705]
- [x] review groups and sharing
- [x] how to define a group that identifies users in a product but enables/disables sharing
   - SOLUTION: standard group associated to a product. If ``read=False``, the group is NOT an association
- [x] Include s4l-lite registered users in product-specific organization
- [x] review "everyone": should be ``read=False``  except for admin?
      - see ``list_user_groups``
- [x] Smaller maintenance/improvements/bugs (moves to  #3816)
