### ISSUE TITLE
Maintenance: fix/add settings command in some of the services's CLI

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3924]
### Motivation

Following up https://github.com/ITISFoundation/osparc-simcore/pull/3703 we created a recipe to produce json-schemas of the settings in every service. The problem is that many of the services in the repository do not have CLI. The recipe looks like:
```makefile

.PHONY: settings-schema.json
settings-schema.json: ## [container] dumps json-schema settings of all services
	@$(MAKE_C) services/api-server $@
	@$(MAKE_C) services/autoscaling $@
	@$(MAKE_C) services/catalog $@
	@$(MAKE_C) services/datcore-adapter $@
	@$(MAKE_C) services/director-v2 $@
	@$(MAKE_C) services/invitations $@
	@$(MAKE_C) services/storage $@
	@$(MAKE_C) services/web/server $@

```
and see that it fails because these three services do not implement ``settings`` command in the CLI

### Task

Implement ``settings`` command in the service's CLI. This can be easily implemented using the helper ``from settings_library.utils_cli import create_settings_command``

1.  create CLI with typer
```python
# cli.py

import logging

import typer
from settings_library.utils_cli import create_settings_command

from ._meta import PROJECT_NAME
from .core.settings import ApplicationSettings

log = logging.getLogger(__name__)
main = typer.Typer(name=PROJECT_NAME)


main.command()(create_settings_command(settings_cls=ApplicationSettings, logger=log))
```
2. add ``entry_points`` in ``setup.py``
```python
    entry_points={
        "console_scripts": [
            "simcore-service-catalog = simcore_service_catalog.cli:main",
        ],
    },
```
3. test and adjust CLI and default environs
```cmd
$ cd services/catalog
$ make install-dev
$ simcore-service-catalog --help
$ make settings-schema.json
```
4. uncomment entry in root's ``Makefile``

```[tasklist]
### Tasks
- [ ] #4148
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/4093
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4331
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/4146
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4337
```

**Comment by mrnicegyu11** [comment]
@pcrespov 
From https://github.com/ITISFoundation/osparc-ops-environments/pull/441 it popped up that `migration` and `director` are still missing the settings command. At least for migration I guess it would be nice if this was present? I am reopening this to raise your attention, but it is not urgent. We can discuss if we want to do it

**Comment by YuryHrytsuk** [comment]
@pcrespov do you have any updates here? Maybe you had a discussion with @mrnicegyu11?

It is the only task left to close https://github.com/ITISFoundation/osparc-ops-environments/issues/177

**Comment by pcrespov** [comment]
> @pcrespov do you have any updates here? Maybe you had a discussion with @mrnicegyu11?
> 
> It is the only task left to close [ITISFoundation/osparc-ops-environments#177](https://github.com/ITISFoundation/osparc-ops-environments/issues/177)

@YuryHrytsuk I would say this is done.
