### ISSUE TITLE
Maintenance: make mypy pass in all services/packages in repo

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4071]
1. ``make mypy`` and fix all errors
2. add ``typecheck`` step in `.github/workflows/ci-testing-deploy.yml` before ``test`` step as
```yaml
      - name: typecheck
        run: ./ci/github/unit-testing/api-server.bash typecheck
      - name: test
        if: always()  <----- NOTE!
        run: ./ci/github/unit-testing/api-server.bash test
```
3. add mypy files ``filter`` in your services
```yaml
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: 
              - 'scripts/mypy/*'
              - 'mypy.ini'
```

### Distribution of tasks

- [x] services/agent  @GitHK
- [x] services/api-server  https://github.com/ITISFoundation/osparc-simcore/pull/4094
- [x] services/autoscaling @sanderegg
- [x] services/catalog https://github.com/ITISFoundation/osparc-simcore/pull/4095
- [x] services/dask-sidecar @sanderegg
- [x] services/datcore-adapter @sanderegg
- [x] services/director-v2 @GitHK
   - https://github.com/ITISFoundation/osparc-simcore/pull/4100
   - https://github.com/ITISFoundation/osparc-simcore/pull/4134
   - https://github.com/ITISFoundation/osparc-simcore/pull/4211
   - https://github.com/ITISFoundation/osparc-simcore/pull/4215
   - https://github.com/ITISFoundation/osparc-simcore/pull/4217
- [x] services/dynamic-sidecar @GitHK
- [x] services/invitations @pcrespov
- [x] services/osparc-gateway-server @sanderegg
- [x] services/storage https://github.com/ITISFoundation/osparc-simcore/pull/4086
- [x] services/webserver @pcrespov @matusdrobuliak66
    - https://github.com/ITISFoundation/osparc-simcore/pull/4102
    - https://github.com/ITISFoundation/osparc-simcore/pull/4105
    - https://github.com/ITISFoundation/osparc-simcore/pull/4113
    - https://github.com/ITISFoundation/osparc-simcore/pull/4145
    - https://github.com/ITISFoundation/osparc-simcore/pull/4131
    - https://github.com/ITISFoundation/osparc-simcore/pull/4183
    - https://github.com/ITISFoundation/osparc-simcore/pull/4186
    - https://github.com/ITISFoundation/osparc-simcore/pull/4187
    - https://github.com/ITISFoundation/osparc-simcore/pull/4188
    - https://github.com/ITISFoundation/osparc-simcore/pull/4189
    - https://github.com/ITISFoundation/osparc-simcore/pull/4190
    - https://github.com/ITISFoundation/osparc-simcore/pull/4196
    - https://github.com/ITISFoundation/osparc-simcore/pull/4198
    - https://github.com/ITISFoundation/osparc-simcore/pull/4199
    - https://github.com/ITISFoundation/osparc-simcore/pull/3774
    - https://github.com/ITISFoundation/osparc-simcore/pull/4219
    - https://github.com/ITISFoundation/osparc-simcore/pull/4209
    - https://github.com/ITISFoundation/osparc-simcore/pull/4230
    - https://github.com/ITISFoundation/osparc-simcore/pull/4256
    - https://github.com/ITISFoundation/osparc-simcore/pull/4304
    - https://github.com/ITISFoundation/osparc-simcore/pull/4317
    - https://github.com/ITISFoundation/osparc-simcore/pull/4339
    - https://github.com/ITISFoundation/osparc-simcore/pull/4328
    - https://github.com/ITISFoundation/osparc-simcore/pull/4340
    - https://github.com/ITISFoundation/osparc-simcore/pull/4334
    - https://github.com/ITISFoundation/osparc-simcore/pull/4327
- [x] packages/dask-task-models-library @sanderegg  
- [x] packages/models-library 
- [x] packages/postgres-database @pcrespov 
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/4307
- [x] packages/service-library
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/4306
- [x] packages/simcore-sdk @sanderegg 
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4400
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4401
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4402
```

**Comment by GitHK** [comment]
dynamic-sidecar already has the checks in place

**Comment by matusdrobuliak66** [comment]
Thanks to good teamwork effort, I can officially close this issue :tada:
