### ISSUE TITLE
webserver meta_modeling fixes and todos

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4124]
- [ ] add call to ``setup_version_control`` instead of dependency to "simcore_service_webserver.version_control",
```python
@app_module_setup(
    __name__,
    ModuleCategory.ADDON,
    depends=[
        "simcore_service_webserver.projects",
        ## FIXME: tmp disabled so it can start "simcore_service_webserver.version_control"
    ],
    settings_name="WEBSERVER_META_MODELING",
    logger=log,
```
- [ ] ``thumbnail`` should be fixed with new models!
```python
            # -------------
            # TODO: hack to avoid validation error. Revisit when models_library.utils.pydantic_models_factory is
            # used to create a reliable project's model to validate http API
            if "thumbnail" in project_as_dict:
                project_as_dict["thumbnail"] = project_as_dict["thumbnail"] or ""
            # ---------------
```
- [ ] Optimize sql queries
```python
    async def get_children_tags(
        self, repo_id: int, commit_id: int
    ) -> list[list[TagProxy]]:
        async with self.engine.acquire() as conn:
            commits = (
                await self.CommitsOrm(conn)
                .set_filter(repo_id=repo_id, parent_commit_id=commit_id)
                .fetch_all(returning_cols="id")
            )
            # TODO: single query for this loop
            tags = []
            for commit in commits:
                tags_in_commit = (
                    await self.TagsOrm(conn).set_filter(commit_id=commit.id).fetch_all()
                )
                tags.append(tags_in_commit)
            return tags
  ```
- [ ]  improve error handling and messages: see new studies error handling solution
```python
def parse_query_parameters(request: web.Request) -> _QueryParametersModel:
    try:
        return _QueryParametersModel(**request.match_info)
    except ValidationError as err:
        # TODO: compose reason message better
        raise web.HTTPUnprocessableEntity(reason=f"Invalid query parameters: {err}")
```
- [ ]  optimize sql queries and add pagination: see solution with latest service version. It includes pagination in db and  https://github.com/ITISFoundation/osparc-simcore/issues/2735
```python
async def _get_project_iterations_range(
    vc_repo: VersionControlForMetaModeling,
    project_uuid: ProjectID,
    commit_id: CommitID,
    offset: int = 0,
    limit: int | None = None,
) -> _IterationsRange:
    assert offset >= 0  # nosec

    repo_id = await vc_repo.get_repo_id(project_uuid)
    assert repo_id is not None

    total_number_of_iterations = 0

    # Searches all subsequent commits (i.e. children) and retrieve their tags

    # TODO: do all these operations in database.
    # TODO: implement real pagination https://github.com/ITISFoundation/osparc-simcore/issues/2735
    tags_per_child: list[list[TagProxy]] = await vc_repo.get_children_tags(
        repo_id, commit_id
    )
```     
- [ ] Idea of marking fields  as``x_mark_name_resource`` to e.g. identify which of the fields are resource names (as defined in https://google.aip.dev/122)  or primary keys in the schemas
```python
class _BaseModelGet(BaseModel):
    name: str = Field(
        ...,
        description="Iteration's resource API name",
        # TODO: PC x_mark_resouce_name=True,  # [AIP-122](https://google.aip.dev/122)
    )
    parent: ParentMetaProjectRef = Field(
        ..., description="Reference to the the meta-project that created this iteration"
    )

    url: HttpUrl = Field(..., description="self reference")
```
- [ ]   check access to non owned projects user_id = request[RQT_USERID_KEY] : https://github.com/ITISFoundation/osparc-simcore/issues/2735
```python
@routes.get(
    f"/{VTAG}/projects/{{project_uuid}}/checkpoint/{{ref_id}}/iterations",
    name=f"{__name__}._list_meta_project_iterations_handler",
)
@login_required
@permission_required("project.snapshot.read")
async def _list_meta_project_iterations_handler(request: web.Request) -> web.Response:
    # TODO: check access to non owned projects user_id = request[RQT_USERID_KEY]
    # SEE https://github.com/ITISFoundation/osparc-simcore/issues/2735

```
- [ ] Enable ``_create_meta_project_iterations_handler`` entrypoint when ``create_or_get_project_iterations`` is implemented: https://github.com/ITISFoundation/osparc-simcore/issues/2735
```python

# TODO: Enable when create_or_get_project_iterations is implemented
# SEE https://github.com/ITISFoundation/osparc-simcore/issues/2735
#
# @routes.post(
#    f"/{VTAG}/projects/{{project_uuid}}/checkpoint/{{ref_id}}/iterations",
#    name=f"{__name__}._create_meta_project_iterations_handler",
# )
@permission_required("project.snapshot.create")
async def _create_meta_project_iterations_handler(request: web.Request) -> web.Response:
    # TODO: check access to non owned projects user_id = request[RQT_USERID_KEY]
    # SEE https://github.com/ITISFoundation/osparc-simcore/issues/2735
```

- [ ] Implement ``_get_meta_project_iterations_handler``:
```python
# TODO: registry as route when implemented. Currently iteration is retrieved via GET /projects/{workcopy_project_id}
@routes.get(
    f"/{VTAG}/projects/{{project_uuid}}/checkpoint/{{ref_id}}/iterations/{{iter_id}}",
    name=f"{__name__}._get_meta_project_iterations_handler",
)
@login_required
@permission_required("project.snapshot.read")
async def _get_meta_project_iterations_handler(request: web.Request) -> web.Response:
    raise NotImplementedError(
        "SEE https://github.com/ITISFoundation/osparc-simcore/issues/2735"
    )
```
- [ ] Error handling and optimze pg query
```python
    # get every project from the database and extract results
    _prj_data = {}
    for item in iterations_range.items:
        # TODO: fetch ALL project iterations at once. Otherwise they will have different results
        # TODO: if raises?
        prj = await vc_repo.get_project(f"{item.project_id}", include=["workbench"])
        _prj_data[item.project_id] = prj["workbench"]
```

**Comment by pcrespov** [comment]
metamodeling&versioning was discontinued in https://github.com/ITISFoundation/osparc-simcore/pull/7182
