### ISSUE TITLE
PublicAPI: studies w/ computational services

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4177]
- Follow from ITISFoundation/osparc-issues#711
-  Entrypoints to be added for new ``studies`` resource:

```[tasklist]
### Tasks
  - [x] get `study` i/o schemas
  - [ ] set `study` i/o data
  - [ ] run `study` (w/ cluster option)
  - [ ] get `study` run log (gather all logs)
```

**Comment by pcrespov** [comment]
# Update [Baklava](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230908_Baklava.md)

- `GET    /v0/files/page`
- `POST   /v0/files/{file_id}:abort`
- `POST   /v0/files/{file_id}:complete`
- `GET    /v0/solvers/page`
- `GET    /v0/solvers/releases/page`
- `GET    /v0/solvers/{solver_key}/releases/page`
- `GET    /v0/solvers/{solver_key}/releases/{version}/ports`
- `GET    /v0/solvers/{solver_key}/releases/{version}/jobs/page`
- `GET    /v0/solvers/{solver_key}/releases/{version}/jobs/{job_id}/metadata`
- `PATCH  /v0/solvers/{solver_key}/releases/{version}/jobs/{job_id}/metadata`
- `GET    /v0/studies`
- `GET    /v0/studies/{study_id}`
- `POST   /v0/studies/{study_id}:clone`
- `GET    /v0/studies/{study_id}/ports`
- `GET    /v0/studies/{study_id}/jobs`
- `POST   /v0/studies/{study_id}/jobs`
- `GET    /v0/studies/{study_id}/jobs/{job_id}`
- `DELETE /v0/studies/{study_id}/jobs/{job_id}`
- `POST   /v0/studies/{study_id}/jobs/{job_id}:start`
- `POST   /v0/studies/{study_id}/jobs/{job_id}:stop`
- `POST   /v0/studies/{study_id}/jobs/{job_id}:inspect`
- `POST   /v0/studies/{study_id}/jobs/{job_id}/outputs`
- `POST   /v0/studies/{study_id}/jobs/{job_id}/outputs/logfile`
- `GET    /v0/studies/{study_id}/jobs/{job_id}/metadata`
- `PUT    /v0/studies/{study_id}/jobs/{job_id}/metadata`
- `POST   /v0/files/content`
- `DELETE /v0/files/{file_id}`
- `DELETE /v0/solvers/{solver_key}/releases/{version}/jobs/{job_id}`


For details, the openapi specs can be found [here](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pcrespov/sandbox-python/329edf00795af4bb0156ac4a99936462f72b4ebc/oas/openapi-dev.json)

**Comment by pcrespov** [comment]
Duplicated https://github.com/ITISFoundation/osparc-issues/issues/1291
