### ISSUE TITLE
Complete workflow for public API clients.

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-simcore#4345]
Develop a workflow (using [openapi-generator](https://github.com/OpenAPITools/openapi-generator)) for generating and mainting both a C/C++ and a Python clients.
Use case: It is important to have up to date clients for communicating with the public API of oSparc. What's important is that we have a workflow for easily generating/testing/publishing clients when we add functionality to oSparc itself.
```[tasklist]
### Tasks
- [x] Fork [openapi-generator](https://github.com/OpenAPITools/openapi-generator) so we can maintain our own templates.
- [x] Support fully automatic generation of the Python client in [osparc-simcore](https://github.com/ITISFoundation/osparc-simcore), via "our" fork of [openapi-generator](https://github.com/OpenAPITools/openapi-generator)
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/40
```

**Comment by bisgaard-itis** [comment]
Closing this issue as all tasks have been achieved
