### ISSUE TITLE
Extend invitations to all products, expose swagger doc (under password) and new e2e test

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4375]
Some actions to follow up on the invitations service

```[tasklist]
### Tasks
- [x] Remove ops-unfriendly characters in env-vars @pcrespov
- [x] https://github.com/ITISFoundation/osparc-ops-environments/pull/183
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4538
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4546
```

**Comment by pcrespov** [comment]
@mrnicegyu11 My part is done here. I assign it back to you.

**Comment by mrnicegyu11** [comment]
Made a PR, assigning it back to you

**Comment by elisabettai** [comment]
Basic question, @pcrespov: I can't find the entrypoint to create new invitations when I go to: https://invitations.osparc.io/dev/doc
Am I looking at the wrong place?
cc @mrnicegyu11

**Comment by mrnicegyu11** [comment]
Hi @elisabettai , good catch this should have reached production but... in the end it didnt, this is a bug. I am now looking into it. I will keep you updated here! Sorry and thanks for letting us know.

**Comment by mrnicegyu11** [comment]
@elisabettai @pcrespov please disregard my previous message, due to our (a bit hacky) hotfix I got confused w.r.t. the dates and which commits are actually rolled out. This has not (via our regular release procedure) propagated to production yet. it will come in the next production release :)

Sorry for the miscommunication!

**Comment by pcrespov** [comment]
> 

@elisabettai FYI note that you need a special user/password to create invitations
