### ISSUE TITLE
New Dockerfile/docker-compose without boot/entrypoint

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4450]
### Is there an existing issue for this?
- [x] I have searched the existing issues

### Planned changes
Example of starting docker container without boot.sh/entrypoint.sh
https://github.com/sanderegg/playground/tree/main/docker_user_group

This is a sub issue from https://github.com/ITISFoundation/osparc-issues/issues/675

```[tasklist]
### Tasks
- [ ] prototype: https://github.com/sanderegg/playground/tree/main/docker_user_group
- [ ] debugpy option for debug and production, remove ptvsd
- [ ] autoscaling
- [ ] webserver
- [ ] api-server
- [ ] director-v2
- [ ] dask-sidecar
- [ ] dynamic-sidecar
- [ ] agent
- [ ] invitations
- [ ] resource-usage-tracker
- [ ] storage
- [ ] osparc-gateway-server
- [ ] datcore-adapter
- [ ] catalog
- [ ] static-webserver
```
