### ISSUE TITLE
Maintenance: All simcore service should be scalable

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4452]
### Is there an existing issue for this?
- [x] I have searched the existing issues

### Planned changes

Any service of the stack should guarantee:
- Can replicate 
- Can be restarted graciously (i.e. saves & recover state)
   - redis?

```[tasklist]
### Tasks
- [ ] Gather knowledge (rationale, techniques, protyptes) @sanderegg @matusdrobuliak66 
- [ ] review and update storage
- [ ] review and update directorv2
```

**Comment by GitHK** [comment]
duplicate we already have an issue for this one #5614
