### ISSUE TITLE
Major upgrade to pydantic 2.0

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4481]
# :skull: :skull: :skull:  Never ever squash commits when updating from master branch :skull: :skull: :skull: 

## Instructions
1. update requirements `make touch update reqs=pydantic`
2. install bump-pydantic `uv pip install bump-pydantic`
3. `bump-pydantic my_package`
4. fix what it did and fix all tests
5. check warnings in the test and finish fixing
6. create a PR and ask for review
7. this PR shall be squash commited

### Planned changes

- Migrate to pydantic >=2.0. See https://docs.pydantic.dev/latest/migration/
- Migrate to fastapi >=0.100  (has ported functionality)

Major upgrade not out-of-the box and requires some coordination.  This upgrade will bring substantial speedup to the code. It would be desirable to measure the improvement. Should we setup some type of benchmark?

Both libraries have been releases so I added a constraint in `requirements/constraints.txt`

We should start testing first the upgrade with the `packages` and then when we understand the migration mechanisms we can do the rest of the repository. 

```[tasklist]
### Tasks
- [x] migrate `settings-library`, specially `CustomBaseSettings` @pcrespov
- [x] migrate `models-library`
```

This is a sub issue from https://github.com/ITISFoundation/osparc-issues/issues/675

```[tasklist]
### MartinKippenberger
- [x] explore the migration path
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6584
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6619
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6580
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6333
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6591
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6517
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6519
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6516
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6513
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6366
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6547
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6534
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6535
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6495
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6508
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6594
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6629
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6632
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6644
```

**Comment by sanderegg** [comment]
@pcrespov explore the migration path

**Comment by giancarloromeo** [comment]
FastAPI doesn't support a mix of pydantic version. The installed one determines the models version and so on.

See: https://github.com/fastapi/fastapi/issues/10360

We will proceed updating the libraries/services one by one. :crossed_fingers:

**Comment by sanderegg** [comment]
packages/models-library/src/models_library/projects.py
![image](https://github.com/user-attachments/assets/2dd594a2-ecb7-44a2-8ce2-199a85253e92)

**Comment by sanderegg** [comment]
@GitHK this looks worrisome
![image](https://github.com/user-attachments/assets/843d8d0c-5f8e-43a7-863a-156e132cd3b9)
