### ISSUE TITLE
Dask backend: Create a separate cluster for group automatically

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4521]
Currently one has to manually create a separate machine in AWS where:
- a docker swarm is created
- a osparc-dask-gateway is started

Once this is done, the use can register the osparc-dask-gateway in oSparc GUI and send computational jobs to that cluster.
Later after use, the cluster is manually terminated.

This needs to be automated. ideally the cluster shall remain up for some time after last use.

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4591
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4602
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4685
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4682
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4703
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4730
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4736
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4738
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4760
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4787
```

**Comment by sanderegg** [comment]
# Proposal

- Create a clusters-manager service in osparc-simcore
  - responsible to create and terminate external clusters in AWS
  - a cluster may be auto-managed (with an autoscaling) or fixed size?
  - a cluster is made of at least 1 computer
  - a cluster is a docker swarm
  - a cluster has a dask-gateway running on the computer
  - a cluster shall have access to the osparc registry and dockerhub (need the correct network setup)
  - a cluster shall be shutdown when it is not used anymore (heartbeat? find out if still in use?)

**Comment by sanderegg** [comment]
Implementation completed during **The Nameless** sprint.

a cluster is created for user/wallet combination for now.
a cluster is:
- 1 machine is created through EC2
- the machine is the manager of a docker swarm
- the machine currently runs a dask-scheduler/dask-worker
- the machine is created through RPC call to the clusters-keeper service
- the clusters-keeper service terminates the machine once it is deemed as unused for more than 5 minutes
