### ISSUE TITLE
Dask backend: autoscaling in osparc-dask-scheduler

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#4522]
When an external cluster is created there must be the following infrastructure available:
- a docker swarm is up
- 1 machine running a dask-gateway, and a dask-scheduler
- X machines running dask-sidecar(s) to run solvers

currently we manually scale the number of machines in that cluster by using the AWS console.
this shall be automated and we could leverage the autoscaling service to this end.

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4709
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4874
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4711
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4764
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4765
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4919
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4942
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4954
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4975
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5010
```

**Comment by sanderegg** [comment]
upscaling will be taken care of in a separate entry
