### ISSUE TITLE
Users can be deleted, their data is deleted

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

As a user, I want to be able to delete my account and be sure that all data which is not anonymized or statistical is deleted. This includes my projects and the associated files. It is very clear to me how collaborators on my shared projects or in a an organization are affected.

## User story:
Minimal:
1: I send a mail with a deletion request to privacy@sim4life.io
2: I get a confirmation that the mail will be processed soon
3: oSparc Backend has functionality to reliably assure data deletion, possibly including from backups
4: Deletion is confirmed via mail

Better version:
1: I click a "Delete my account" button in the account settings
2: I get presented a list of the affected projects / files and what will happen with them. I am told that there is no way back, my data cannot be recovered.
3: I confirm the deletion again
4: My account is deleted
5: I get a "sad to see you go" goodbye confirmation via mail

### Definition of Done

User story is in
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4871
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4908
```
