### ISSUE TITLE
Broadcast email to users

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4638]
As an oSparc Product platform operator (or developer), I want to be able to send a broadcast e-mail to either a given group of users or all users part of a given oSparc group. These e-mails should use the already present HTML email style. The usecase is to inform users about platform malfunctions, or even inform them about new features or ask them to partake in surveys, etc.

#### Tasks
- [ ] Properly send mass emails (avoid getting in spam filters) @giancarloromeo @YuryHrytsuk 
- [ ] GDPR-like concerns (unsubscribe button? user consent? ...) @YuryHrytsuk 
- [ ] Track email metrics (spam metrics, AWS SES limits, ...) @YuryHrytsuk 
- [ ] Use only in deployment having dedicated email infrastructure (email server, domain, user, ...) @giancarloromeo 

### Definition of Done

Minimal:
There is a REST API entrypoint which can be used to broadcast an email to all users of one simcore group

Enhancement:
There is a REST API entrypoint which can be used to broadcast an email to a given list of users.

**Comment by odeimaiz** [comment]
> [@odeimaiz](https://github.com/odeimaiz), sending max 10 Emails/Minute will require a change in the current UI/UX. We can't block the dialog until the operation is completed. I add a [ ] above, so we can discuss this later.

Yep, what about when you start the long running task, I display "emails are on their way" and we show the LRN in the navbar's cog?

**Comment by YuryHrytsuk** [comment]
Bugs:
- [ ] `1.0 OP_Q_ENCODED_FROM looks like a different letter` which is probably caused by custom display from `?utf-8?q?o=C2=B2S=C2=B2PARC?=` -> is in MIME encoded-word format - defined in RFC 2047 - used in email headers when they contain non-ASCII characters (in this case squared 2 in o2S2PARC) @giancarloromeo 
- [x] after re-login notification tasks do not include `title` in progress reports sent to frontend @giancarloromeo https://github.com/ITISFoundation/osparc-simcore/issues/8997
- [ ] frontend glitches when progress cog is not shown at all @odeimaiz
