### ISSUE TITLE
Payments methods: add, remove, list and auto-recharge

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4751]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4747
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4826
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4953
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4979
- [x] Connect to payments-gateway @pcrespov with Dennis
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5036
```
