### ISSUE TITLE
Extension of Products: credit prices, login-per-product, PRODUCT_OWNER role and invitations

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4752]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4758
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4796
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4844
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4850
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4862
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4546
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4914
```

**Comment by pcrespov** [comment]
## Update 7Peaks

Everything in the tasks implemented except:

- login per product https://github.com/ITISFoundation/osparc-simcore/pull/4947. Necessary strictly give access to users only to the products they are registered to (e.g. an academia user might not have access to pro or viceversa)
- https://github.com/ITISFoundation/osparc-simcore/pull/5055. Necessary to create invitations that allow a user to register in a new product
