### ISSUE TITLE
SPARC Model Integration (MS10,D10)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#493]
**Placeholder**
There will be models from SPARC teams that have to be ported to oSPARC

**Already Expected**
- [x] Ward model (currently MATLAB, includes machine learning)
- [x] beautify ward if possible
- [x] fast clancy workflow (#776 )
- [x] if reasonable: viewer for simplified yoon-sun (e.g., remote rendering mode of paraview, in combination with simplified yoon-sun surfaces) (#650)
- [x] workflow that gets predefined data set from portal/dat-core and displays it within paraview (e.g., rendering of EM simulation results) and in rawgraph (#777)
- [x] opencor workflow with map-core (#495)
- [x] Bornstein model (NEURON - see Case #493)
- [x] Note: removed services are: Kember
