### ISSUE TITLE
Computational clusters: Allow to define cluster concurrency

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5074]
As a user I want to be able how many jobs/computational services can run in parallel on machines of the same type

```[tasklist]
### Tasks
- [ ] Add RPC/Rest entrypoints in autoscaling to allow to GET/PATCH number of concurrent jobs
- [ ] Director-v2/webserver shall provide an entrypoint to set the concurrency
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5180
```
