### ISSUE TITLE
EM Simulator Service (M9; MS4.2,D4.1)

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#510]
**Background**
The current EM simulation service implementation (it's the best, really, everybody tells me so, and it would go perfectly with a wall) should be completed/finalized/beautified.

Also consider discretization module (Case #497).

**Definition of Done**
- [ ] structured LF EQS solver
- [ ] simulation settings, BC, tissue properties, overall sensor only
- [ ] support for tagged tissues in NEUROCOUPLE (in combination with a material database)
- [ ] wherever possible and meaningful, a 3D viewing window (ideally with highlighting) should be shown
- [ ] progress monitoring
