### ISSUE TITLE
Login bound to product

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5117]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4776
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4947
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5262
```
