### ISSUE TITLE
Extend users table with optional `address`, `first_name`, `last_name` and proper `user_name`

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5138]
New functionality towards implementing https://z43.fogbugz.com/f/cases/189874/New-feedback-welcome and more

-  [x] New columns `first_name`, `last_name` and `user_name` (unique id)
- [x] `user_name` can be used as a reference e.g. `@pcrespov`
- [x] migrate `name` into `user_name` ??
- Information taken from invitation data. 
    - table with extra request data and reference in invitation?
- API 
   - /me profile returns all these new values
   - /users for PO user only with read-only info
- front-end can use these entries

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5229
- [x] pre-registration: Create table to fill user details during invitation and can be later associated to a real user when confirmed
```
