### ISSUE TITLE
redirect logs of computational clusters to graylog

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5146]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5141
- [x] set up custom boot scripts to redirect logs to graylog in workers
- [x] set up custom boot scripts to redirect logs to graylog in primary machines
```
