### ISSUE TITLE
Removing `s4l` product from `osparc.io`

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5337]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/564
- [ ] remove all associations to `s4l` group, i.e. users and services @pcrespov 
- [ ] Move all studies for each user in `s4l` into an `archive-sim4life.cloud` folder in their corresponding accounts of `sim4life.io` 
```

**Comment by pcrespov** [comment]
Replaces https://github.com/ITISFoundation/osparc-ops-environments/issues/561
