### ISSUE TITLE
Platform Resource Management

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#54]
**GOAL**
As DevOps, I want to have full control of hardware resources consumed by the platform. I also need good monitoring/logging/debugging tools to keep track of issues and problems.

**Lifetime of Services**
- [x] if a user logs out of the platform, resources should automatically be freed
- [x] after a long time of inactivity, resources should automatically be freed

**Protocol for Problem Handling**
- [ ] what to do if a node fails
- [ ] what to do if a service fails

**Monitoring Tools**
- [x] access to swarm logs
- [x] access to node logs
- [x] access to service logs
- [x] look into available tools, i.e., docker EE

**Hardware Allocation**
- [ ] automation of cloud resource management
- [ ] integration into scheduler

**Comment by oetiker** [comment]
resources should probably be logged 'per user' so that we know who is causing the damage

**Comment by esraneufeld** [comment]
high priority (to be addressed for now):
- Lifetime of Services

**Comment by sanderegg** [comment]
State:
 - book-keeping of services started by user/study for each opened browser tab:
    1. by monitoring websocket connection/disconnection (1 websocket per browser tab)
    2. store resources in external InMemory data store "Redis" to allow scaling of webserver in case of heavy load
- allows auto-de-allocation of services when:
  1. browser tab is closed
  2. user logs-out
  3. user disconnects for X amount of time
  4. user is inactive for Y amount of time
  5. anonymous user closes tabs or is inactive

- deleting of project deletes all project resources, e.g. services, internal data and database entries

**Comment by sanderegg** [comment]
State:
- book-keeping of services started by user/study for each opened browser tab:
  - by monitoring websocket connection/disconnection (1 websocket per browser tab)
  - store resources in external InMemory data store "Redis" to allow scaling of webserver in case of heavy load
- dynamic services are now auto-deallocated when:
  - browser tab is closed
  - user actively logs out (will also logout any other browser tab open of the same user)
  - user disconnects for more than 30 minutes (network down), during that time the services are kept up
  - user closes a project by going to the dashboard (unless another tab is still opened)
- deleting a project deletes the project resources
- deleting a node inside a project deletes the nodes resources
