### ISSUE TITLE
External clusters: Provide metrics of all of them clusters for prometheus

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5493]
Currently the dask-scheduler of each cluter is metrics-enabled.
But, by the very nature of these external clusters they are autoscaled, and prometheus does'nt know where to scrape them.

Therefore we would need one centralized location to scrape these schedulers, which gives for now 2 options:
- Option 1: Clusters-keeper could provide a /metrics endpoint that aggregate the /metrics endpoint of all the scheduler it created
- Option 2: have an exporter that scrapes the external clusters
- Option 3: have autoscaling instrumented + have a prometheus running on every computational clusters, then make central prometheus auto-discover them via service discovery via EC2
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5528
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5530
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/619
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5544
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5552
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/629
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5609
```

**Comment by sanderegg** [comment]
completed
