### ISSUE TITLE
App-team admin pannel

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5608]
The PO center will move into an independent service and accessible via an isolated subdomain  (e.g. `admin.foo.com`). The design should acomplish
1. Independent release (i.e. can independently provide)
2. Fast dev iterations ( panels from prototype to deploy )
3. Focus on feature than looks

```[tasklist]
### Tasks
- [ ] New service with read access to data-sources (database, grafana panels?)
- [ ] PO-center enhancements: send invitation email by adding `fogbugz` issue
- [ ] PO center reports: users registration status
```
