### ISSUE TITLE
🏗️ Clean-Up and Audit tip.itis.swiss

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#5628]
This is a sub issue from https://github.com/ITISFoundation/osparc-issues/issues/1309

As agreed, this is a nice opportunity to purge unused products, templates etc. from the DB, before the data is migrated to tip.science on AWS.
```[tasklist]
### Tasks
- [x] product tip as billable
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5627
- [x] price per credit
- [x] pre-register current users
- [x] user wallets
- [x] services registry: which services and access to product, vendor secrets & variables
- [x] pricing plan
- [x] buffer machines? ec2 instances?
- [ ] wishlist of refactoring and tooling to migrate or move accounts or data among deploys
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5635
```

- Est: 2 days

**Comment by matusdrobuliak66** [comment]
**Discussion about wallets:** 
- We thought the best idea would be to use PO "personal wallet", which PO share with users. That way, PO only need to manage one wallet. We can rename it to something more appropriate, like 'TIP free credits,' and as a benefit, PO will see all usage of everybody. 
- We will connect the new TIP deployment with the testing Stripe account, which will allow PO to add additional credits or to turn on the auto-recharge functionality
