### ISSUE TITLE
Setup E2E tests on TIP

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5630]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5709
- [x] setup e2e ops tests [YH]
- [ ] setup e2e status tests
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5819
```

**Comment by SCA-ZMT** [comment]
`setup e2e status tests` is not checked but the issue has been moved to Done, may I close it? @odeimaiz @pcrespov

**Comment by YuryHrytsuk** [comment]
I would say no. This is still not in

**Comment by sanderegg** [comment]
@YuryHrytsuk is the status check now in?
