### ISSUE TITLE
Run demo on master.osparc.io

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#5694]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1389
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1390
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5699
- [ ] enable DEV_FEATURES for the api-server in staging and production @pcrespov @bisgaard-itis
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5696
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5741
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5707
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5715
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5803
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5796
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5783
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5724
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/150
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5729
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5734
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5742
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5745
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5714
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5750
- [ ] Release to production: api-server entrypoints https://github.com/ITISFoundation/osparc-simcore/pull/5792
- [ ] Release to production: osparc-meta-parallel-runner, osparc-meta-dakota (give access Luca) @wvangeit
- [ ] Release to production: osparc client @bisgaard-itis
```

**Comment by wvangeit** [comment]
@pcrespov @bisgaard-itis You think it would be difficult to implement?
https://github.com/ITISFoundation/osparc-issues/issues/1393

When I'm running many (exactly the same in parallel), some (very few) start returning a 'FAILED' status after some 'RUNNING' statuses. Probably the easiest to debug this, is for my script to fetch the logs from the api.

What do you think?

**Comment by bisgaard-itis** [comment]
> @pcrespov @bisgaard-itis You think it would be difficult to implement? [ITISFoundation/osparc-issues#1393](https://github.com/ITISFoundation/osparc-issues/issues/1393)
> 
> When I'm running many (exactly the same tasks, in parallel), some (very few) start returning a 'FAILED' status after some 'RUNNING' statuses. Probably the easiest to debug this, is for my script to fetch the logs from the api.
> 
> What do you think?

Adding the logfile endpoint should be very easy. I assume it should do exactly the same as the solver log file endpoint. So it is just a matter of refatoctoring that. I can take care of that on monday.

**Comment by wvangeit** [comment]
I'm always using this script: https://github.com/wvangeit/osparc-pyapi-tests/blob/master/noninter1/README.md
I now added a 'make parallel' target for that script. Need to have the linux 'parallel' command installed for that etc.

**Comment by wvangeit** [comment]
I'm closing this particular issue, because we did run the demo. I've moved all the remaining issues/bugs we found in the underlying platform to: https://github.com/ITISFoundation/osparc-issues/issues/1407
