### ISSUE TITLE
Extend captures used to mock backend responses

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5705]
- We aim to **Auto generate** mock captures using `pytest` CLI  and a `local` deploy
	- PROS:
		- we enforce user to create the test first +++
		- avoid capture code in production +++
		- can recreate better and easier captures: follows up comment by MD https://github.com/ITISFoundation/osparc-simcore/pull/5660#pullrequestreview-2005736942. +++
		- can be reused to capture `httpx` calls to external services ++
		- can be reused in any other service, not only api-server
	- CONS:
		- cannot  generate mock using swagger anymore ++
		- cannot generate mock against non-local backend stack +		  
- The idea is that we write the test first e.g. `test_with_client_calls`
- Then we start the stack in local mode `make up-devel` and **setup** an initial state (e.g. a user in the db, etc...)
- Then we run the test against installed `api-server` and this one makes calls to the local stack (where all services in the stack are accessible from host)
	- (still not happy with option names etc ...)
```
pytest --capture-backend-path=path/to/capture.log -k test_with_client_calls tests
```

----

- These CLI options will enable
	- spy `httpx` requests to all selected clients within  `osparc_simcore_api_server`
	- dump logs in `capture-backend-log-path`
	- fail if `local` is not up and running (i.e. ready)
- Move as fixtures to `pytest-simcore`
	-  mv code from api-server  -> `pytest-simcore`
	-  rm all the env vars
	-  new fixtures for clients and spy on X-server internal clients
- Support [iterators as side-effect](https://lundberg.github.io/respx/guide/#mock-with-a-side-effect)
	- find sequences in list of captures (explicit labeled or implicit)
	- 
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5727
- [ ] Enable recreation of mocks using pytest's  CLI
- [ ] rm all captures mechanism from `api-server`
```
