### ISSUE TITLE
RClone errors go undetected

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5778]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which deploy/s?

production aws (e.g. osparc.io)

### Current Behavior

in sim4life.io.

A user got a dynamic service failed start.

After logs analysis it can be found that there is some file corruption, one file MD5 computation failed during the RClone transfer.

### Expected Behavior

If an error occurs while transfering, it should either abort right away and/or clearly inform the user of what is broken.

### Steps To Reproduce

1. Install RClone
2. Rclone sync the directory

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5789
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5793
- [x] @GitHK why do we have retries in RClone call when the call is already retried as well? all clear only happens on specific exception from storage service
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5830
```

**Comment by sanderegg** [comment]
and a graylog link: https://monitoring.sim4life.io/graylog/search?q=%22md5+hash+differ%22&rangetype=relative&from=432000

**Comment by sanderegg** [comment]
some ec2 serial console error:


![Image](https://github.com/ITISFoundation/osparc-simcore/assets/35365065/8a79b713-16db-4f04-9a84-1c2bf581c06a)

some rclone issue possibly related (1.64.0)
https://forum.rclone.org/t/rclone-generating-kernel-panics/42378


some info about the rcu-sched:
https://askubuntu.com/questions/1114612/rcu-sched-self-detected-stall-on-cpu-watchdog-bug-soft-lockup-cpu3-stuck

**Comment by sanderegg** [comment]
The above mentioned issues are still there (detection of errors, fail fast not working) but the biggest problem is gone (hanging machines).
Therefore this issue is closed and a new one for replacing RClone created [there](https://github.com/ITISFoundation/osparc-simcore/issues/5833)
