### ISSUE TITLE
Full implementation of all missing study api endpoints https://github.com/ITISFoundation/osparc-issues/issues/1291

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-simcore#5814]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1394
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1392
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1393
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5690
```
