### ISSUE TITLE
Upgrade to python 3.11

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#5854]
### Planned changes

```[tasklist]
### Tasks
- [x] Check all requirements can run with py 3.11
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6240
- [x] Upgrade dockerfiles base
- [x] Add in PR link to highlights of new language
- [x] Check promised speed-up (e.g. if CI implemented, selected tests should go faster than before)
```

**Comment by pcrespov** [comment]
@giancarloromeo pylint for 3.12 still missing! :-)

**Comment by giancarloromeo** [comment]
Yup, actually it's in another issue: https://github.com/ITISFoundation/osparc-simcore/issues/6240 but I can continue this one
