### ISSUE TITLE
Use initialized EBS storage instead of buffer machines

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5864]
## Concept
Instead of keeping running EC2 instances as buffer machine, we would only keep their respective EBS volumes up.

### AMI:
- current boot script automatically uses the largest disk it finds to mount the docker folder, needs to change to only target EBS
- needs to set an EBS disk
- currently large EC2s have a larger disk (up to 3.4TB which is free of charge and available to the users), need an equivalent EBS? when yes we need to parametrize this and define what sizes are needed
### Autoscaling:
- when an EC2 is started it received the "UserData" script that "pre-pulls" docker images such as s4l that is large,
- instead of keeping X running buffer machines, it would stop them instead and terminate the ones that are above the buffer number,
  - it must wait until the pre-pulling took effect **before** stopping the machines and I think there is no way but SSH in order to know that and that is not very nice, investigate some other way (maybe start with a hard-coded delay)
  - it must handle the disks data (images will accumulate over time and fill the disk), how?
  - if we only stop instances, then we need to book keep the available stopped instances. what is the advantage over shutting them down?
  - we need to book keep the created volumes and ensure they do not accumulate

```[tasklist]
### Eisbock
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6227
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6230
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6238
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6242
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6250
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6251
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6252
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6299
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6254
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6314
```
 
```[tasklist]
### Tasks
- [x] Modify AMI boot script to optionally skip instance storages
- [x] Have only 1 AMI with 500GB additional EBS disk?
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6032
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5923
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6097
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6045
- [x] Tune up disks (throughput + IOPS) on root drive and docker drive --> using maxed out GP3s
```

**Comment by matusdrobuliak66** [comment]
https://depot.dev/blog/faster-ec2-boot-time

**Comment by sanderegg** [comment]
regarding autoscaling, I see currently 2 option:

## pre-create complete EC2s:
1. start buffer machine of cheap type (such as t3.medium or so)
2. ensure startup is complete (such as pre-pulling) - using SSH, AWS SSM or hard-coded time
3. stop machine (only the EBS disks are left to pay (8GB root + 500GB docker))
4. when there is need for a new machine, first check if any stopped buffer machine is available, if yes set the correct type and start it
5. when the machine is not needed anymore, instead of shutting it down, it can be passed to the buffer handler
6. we might need to ensure the disk is cleaned between runs
7. we need to monitor the EBS volumes/stopped machine and possibly remove them

## only keep initialized EBS volumes
1. start buffer machine of cheap type
2. ensure startup is complete
3. shutdown machine but keep EBS volume
4. when there is need for a new machine, first check if we have free EBS volumes around, if yes use them
5. monitor EBs volumes
6. handle cleanup of volumes

**Comment by sanderegg** [comment]
## User story
- Prepare background on how this new system works
- Show measurements, and how is it changing
- Show costs and how it is changing

**Comment by sanderegg** [comment]
Create a graph of responsiveness vs costs for:
- current buffer system
- new EBS buffer system
