### ISSUE TITLE
Mount EFS to sidecar

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-simcore#5872]
- Mount EFS to sidecar
```[tasklist]
### Tasks
- [x] Add moutning of EFS to Ansible script
- [x] Mount docker volume connected to efs to Efs Guardian Simcore service
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/687
- [ ] Efs Guardian should be able to create directory in the EFS and expose this as RPC
- [ ] Mount correct directory in EFS to dynamic sidecar
```
