### ISSUE TITLE
resource usage tracker shall keep track of parent project/node IDs

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5878]
```[tasklist]
### Tasks
- [x] migrate database to get the optional parent project UUID and parent node ID
- [x] upgrade pub/sub call to pass the necessary fields
- [x] return these fields to the frontend
```

**Comment by sanderegg** [comment]
all completed
