### ISSUE TITLE
Storage: refactor copying of projects

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#5940]
When copying projects at scale (currently only 10-20...), storage might enter a bad state where it cannot handle single requests anymore.

The current implementation of ```POST /v0/simcore-s3/folders``` locks 4 DB connection at a time while S3 copying is completed.
If there are many files being copied, or the entrypoint is called many times in parallel this is highly inefficient and leads to blocking storage from doing anything.

The current implementation locks the DB transaction while the copying runs because:
- such that in case of S3 issue the DB entry is automatically rolled back. This would be ok provided the S3 call is fast, which it is not. Even worse it can take minutes as the file size might be huge.
- since storage actively looks for expired multipart uploads, they need to be registered in the file_meta_data table as such before the copy/upload takes place

A better way is probably to copy all the files via S3 calls first, then update the file_meta_data table once this is done.
Since AWS provide a way to define Expiring multipart upload IDs, this should be used instead of storage doing the cleaning.

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/702
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5975
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5976
```

**Comment by bisgaard-itis** [comment]
Here's some food for thought: Several of the issues we encounter with the metamodeling comes from the fact that we have to copy/clone an entire project when running a study. This means that running a study job (in the sense of the api-server) creates a clone of the project in s3. This can potentially lead to a huge amount of data and moreover it is quite inefficient. One reason why we need this is that our projects are not version controlled. If our projects were version controlled one would simply specify a commit with which the project should run. Note that cloning the projects is also the source of https://github.com/ITISFoundation/osparc-simcore/issues/5803. So in addition to improving storage it might be worth considering if we could version control our projects.

**Comment by wvangeit** [comment]
I also discussed this with @matusdrobuliak66 a bit this week. An other option is to have some filesystem-based snapshot mechanism that we would use.
If we could e.g. just mount a snapshot of a study, thinks would be fairly easy. That could also be a read-only mount in case one wants to investigate a study somebody else has open.

**Comment by bisgaard-itis** [comment]
> I also discussed this with @matusdrobuliak66 a bit this week. An other option is to have some filesystem-based snapshot mechanism that we would use. If we could e.g. just mount a snapshot of a study, things would be fairly easy. That way we could also be a read-only mount in case one wants to investigate a study somebody else has open.

Here you mean mount when running the job?

**Comment by wvangeit** [comment]
Well yeah, when you start a job, you create a snapshot of the study's disk space, and run your job from that one.

**Comment by wvangeit** [comment]
(I was mostly discussing with @matusdrobuliak66 because we picking a networked file system it could be good to check if it would have such capabilities or not)

**Comment by bisgaard-itis** [comment]
> (I was mostly discussing with @matusdrobuliak66 because we picking a networked file system it could be good to check if it would have such capabilities or not)

OK, interesting idea. I suspect it would be more flexible to actually version control our projects. But if the file system thing would fit with this then that would of course be very nice

**Comment by wvangeit** [comment]
The question is what you define as 'version control'. You mean git or so?
Since these projects could potentially be huge with lots of binary files, i would do it at a lower level. But anyhow, to be discussed.

**Comment by bisgaard-itis** [comment]
> The question is what you define as 'version control'. You mean git or so? Since these projects could potentially be huge with lots of binary files, i would do it at a lower level. But anyhow, to be discussed.

The tool I know for doing this with large amounts of data is https://github.com/iterative/dvc. We already use it in the Sim4Life desktop team. This would essentially be a replacement for RClone which we currently use to synchronize data in the running container with S3. The way DVC is intended to be used is with Git. It adds every "large" file to the .gitignore and computes a small file with metadata which is commited into the Git repo. Among other things this metadata file holds a checksum of the large file. 

Tbh I don't really mind if it would be DVC or another tool. I know there are good alternatives for combining Git with large files and DVC is just the one I know, so that's why I mention that one. For me the key feature which would bring several big advantages would be to use proper version control. One of them would be to get rid of the cloning of projects when submitting jobs in metamodeling, but another would be from a user perspective, to just have different branches with code/data and being able to easily revert changes. One nice thing about DVC is that this offers essentially the functionality you would hope to have from Git. E.g. you can do a `dvc diff` to check what your changes are. Currently, if you have two versions of your project in osparc that is not easy to achieve. To me the fact that we can't pin a version of a project (a snapshot) is a big limitation and I am convinced we would find other places in the code where this would be a big advantage. In general I think the fact that we have to lock the db/redis whenever we touch a file is unfortunate. My understanding is that we do that because we are afraid a user with access to it could modify it. With version control you don't really have to worry about that because a change to the file results in a different commit in the backend.

**Comment by sanderegg** [comment]
Before we start changing technology, I would be very happy that we list what the requirements are and what we want to achieve, also it should be backwards compatible. I am against making special ways just for the public API if it does fulfil what the current GUI does. That means, that the current tech stack must be migrated in any case.
Nevertheless I find very problematic now that we are running behind issues because we totally opened the gates without limits in production. 


Anyway, I am not sure I understand whether the DVC is really needed here, S3 is made for large files already. I think the issues currently are:
- access to the database when copying that is locked while copying is going on (and this is due to the multipart upload), which means that you cannot copy more than 12 projects at one time,
- we could also have a copy-on-modify policy,
-

**Comment by bisgaard-itis** [comment]
> Before we start changing technology, I would be very happy that we list what the requirements are and what we want to achieve, also it should be backwards compatible. I am against making special ways just for the public API if it does fulfil what the current GUI does. That means, that the current tech stack must be migrated in any case. Nevertheless I find very problematic now that we are running behind issues because we totally opened the gates without limits in production.
> 
> Anyway, I am not sure I understand whether the DVC is really needed here, S3 is made for large files already. I think the issues currently are:
> 
>     * access to the database when copying that is locked while copying is going on (and this is due to the multipart upload), which means that you cannot copy more than 12 projects at one time,
> 
>     * we could also have a copy-on-modify policy,

Makes sense. Let's discuss in the meeting today

**Comment by sanderegg** [comment]
I will also add here a few things to think about:
- have storage use a separate DB than the rest of simcore platform (as scaling them will invariably hit the limit of the number of clients on postgres)
- totally ditch storage database
- use AWS ElasticCache and check the best practices listed on that page: [https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/using-caching-for-frequently-accessed-content.html](https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/using-caching-for-frequently-accessed-content.html)
-
