### ISSUE TITLE
🚀 Release v1.76.0

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-simcore#6046]
### Release version

1.76.0

### Commit SHA

`719aed92c3dfee9d82935d78f5d61d143f240e92`

### Previous pre-release

https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_Eisbock2

### Did the commit CI suceeded?

- [X] The commit CI succeeded.

### Motivation

- Regular sprint release

### Changes
* https://github.com/ITISFoundation/osparc-simcore/pull/6026 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/6025 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6032 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6037 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6038 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6034 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/6027 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6036 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6042 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6047 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/6039 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6033 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6049 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6051 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/6048 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6053 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5923 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6052 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6050 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/5942 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5916 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6065 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/6064 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/6058 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6067 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6066 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6069 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/6061 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6073 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5961 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/6077 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6070 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6060 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6079 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6082 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6083 by @bisgaard-itis
* https://github.com/ITISFoundation/osparc-simcore/pull/5990 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6071 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6035 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6084 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6089 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6090 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6085 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6091 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6016 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6093 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6088 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6094 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6080 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6098 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6100 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6096 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6104 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6102 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6109 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6111 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6108 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6114 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6106 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6110 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6112 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6107 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6116 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6120 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6117 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6121 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6122 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/5983 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6118 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6097 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6124 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6129 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6128 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6138 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6119 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6125 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6140 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6139 by @ignapas
* https://github.com/ITISFoundation/osparc-simcore/pull/6137 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6144 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6072 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6147 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6132 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6127 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6149 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6150 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6152 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6145 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6154 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6146 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6158 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6160 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6161 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6162 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6134 by @dependabot
* https://github.com/ITISFoundation/osparc-simcore/pull/6163 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6131 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6167 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6169 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6172 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6174 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6171 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6177 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6153 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6181 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6179 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6182 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6176 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6180 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6183 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6187 by @mrnicegyu11
* https://github.com/ITISFoundation/osparc-simcore/pull/6155 by @matusdrobuliak66
* https://github.com/ITISFoundation/osparc-simcore/pull/6164 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6188 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6184 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6151 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6192 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6198 by @sanderegg
* https://github.com/ITISFoundation/osparc-simcore/pull/6196 by @pcrespov
* https://github.com/ITISFoundation/osparc-simcore/pull/6126 by @GitHK
* https://github.com/ITISFoundation/osparc-simcore/pull/6197 by @odeimaiz
* https://github.com/ITISFoundation/osparc-simcore/pull/6206 by @odeimaiz
_No response_

### Devops before 👷
- [x] Fix videostreaming. 
   - [x] Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/729
   - [x] nih prod apply
   - [x] sim4life apply
   - [x] aws tip apply
   - [x] Remove `osparc-sim4life-GPU` 
   - [x] Remove extra db changes made for Nik @mguidon 
- [x] CEPH Lifecycle Policies. 
  - [x] Merge and apply https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/654
  - [x] Merge and apply after the one above https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/
  - [x] Run CEPH Ops pipelines
  - [x] ITISFoundation/osparc-ops-environments#765
- [x] Update SSL Certs:
  - [x] nih prod --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/pipelines/842396
  - [x] sim4life --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/pipelines/842962
  - [x] aws tip --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/pipelines/843063
  - [x] inhouse tip --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/pipelines/842397
  - [x] dalco prod --> https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/pipelines/842398
- [x] Merge and apply: [ec2 ssm readonly role in sim4life](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/706)
- [x] Merge and apply: [ec2 ssm readonly role in aws tip](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/707)
  - [x] merge conflict for env `EC2_INSTANCES_ALLOWED_TYPES`
- [x] Redis password 
  - [x] Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/722
  - [x] ensure it works
    - [x] inhouse tip
    - [x] aws tip
    - [x] sim4life
    - [x] nih prod
    - [x] dalco prod
- [x] Move appmotion db on AWS RDS
  - [x] sim4life --> https://github.com/ITISFoundation/osparc-ops-environments/issues/766
    - [x] copy data
    - [x] merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/739
    - [x] update credentials page
  - [x] aws tip
      - [x] move data 
      - [X] merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/740
      - [x] update credentials page --> https://github.com/ITISFoundation/osparc-ops-environments/issues/766
  - [x] Force restart `appmotion_gateway` is required (https://github.com/ITISFoundation/osparc-ops-environments/pull/724
    - [x] sim4life
    - [x] aws tip
  - [x] Manually remove `appmotion_gateway` stack from NIH PROD
  - [x] Check video streaming works on AWS @matusdrobuliak66 @YuryHrytsuk 

### Devops after 👷
- [ ] ITISFoundation/osparc-ops-environments#767

### Summary 📝

- [x] Prepare release link
```cmd
make release-prod version=<M.m.0>  git_sha=<commit_sha>
```
- [x] Draft [release changelog](https://github.com/ITISFoundation/osparc-simcore/releases)
- [x] Announce maintenance ( ** ANNOUNCE AT LEAST 24 HOURS BEFORE ** )
- redis add an entry in db `scheduled_maintenance` with key `maintenance` ``{"start": "2023-03-06T13:00:00.000Z", "end": "2023-03-06T15:00:00.000Z", "reason": "Release <vX.X.0>"}``. Note the time is in UTC, please adjust accordingly
    - [x] aws
    - [x] dalco
    - [x] tip
- status page (https://manage.statuspage.io/)
    - [x] osparc
    - [x] s4l
- mattermost channels
    - [x] maintenance
    - [ ] power users

### Releasing 🚀

- [ ] Maintenance page up.
```cmd
cd /deployment/production/osparc-ops-environments
make up-maintenance
make down-maintenance
```
- [ ] Release by publishing [draft](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Check release CI
- [ ] Check hanging sidecars. Helper command to run in director-v2 CLI `simcore-service-director-v2 close-and-save-service <uuid>`
- [ ] Check deployed
  - [ ] aws deploy
  - [ ] dalco deploy
  - [ ] tip deploy
- [ ] Check testing endpoint ex. `https://testing.osparc.speag.com/`
- [ ] Delete announcement
- [ ] Check e2e runs
- [ ] Announce
``` md
:tada: https://github.com/ITISFoundation/osparc-simcore/releases/tag/v<M.m.0>
```

**Comment by mrnicegyu11** [comment]
!!! This has to be merged https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/722

**Comment by mrnicegyu11** [comment]
!!! this has to be merged and tf-applied https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/729

**Comment by matusdrobuliak66** [comment]
:warning: If RClone replacement with AWS CLI goes well, `AWS_S3_CLI_S3` var should be filled in production

**Comment by matusdrobuliak66** [comment]
What should be tested?
 - We were refactoring projects access rights. Therefore anything connected to sharing of projects I would like to be tested. 
 - We had issues with file picker, anything connected to file picker should be tested. (ex. 1. not owner opens a study that was shared with him and tries to download file picker content, 2. having multiple filepickers connected to dynamic service, check whether files were correctly donwloaded to dynamic service)

**Comment by matusdrobuliak66** [comment]
### Planned release: 22.8.2024 8:00 - 12:00 Zurich time

**Comment by matusdrobuliak66** [comment]
- [ ] @mguidon publish new sim4life services

**Comment by matusdrobuliak66** [comment]
# Hotfix v1.76.1
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/commit/e1bfd62d5abd8c026f9dda0330a6d3f8e310cd34

**Comment by YuryHrytsuk** [comment]
### Issues
* no maintenance can be run because repo.config cannot be created because terraform needs to be run first
* NIH STAG has out-of-date credentials for appmotion db

**Comment by matusdrobuliak66** [comment]
# :warning:  Additional manual hotfix:
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/commit/400e0b55c4af5b22191d6d4b22172e828b0ead1b

:warning: Manually changed static-webserver with: `itisfoundation/static-webserver:hotfix-github-2024-08-22--16-29.400e0b55c4af5b22191d6d4b22172e828b0ead1b` image :warning:

**Comment by matusdrobuliak66** [comment]
# :warning: Additional manual hotfix: 
- Cheery pick:
:warning: Manually changed **static-webserver** with: `itisfoundation/static-webserver:hotfix-github-2024-08-30--13-13.62edb69bb89170c1e19a6fae8621093e3710d68e`

**Comment by matusdrobuliak66** [comment]
# :warning: Additional manual hotfix: 1.76.4
- Cheery pick: https://github.com/ITISFoundation/osparc-simcore/commit/40582418b7b7458e3ecbf051f4819bdb11d2cf68

:warning: Manually changed **static-webserver** with: `itisfoundation/static-webserver:hotfix-github-2024-09-02--15-41.f0041842639e59b0920e610f8ff7de3ebb33e7a6`

**Comment by sanderegg** [comment]
# :warning: Additional manual hotfix: 1.76.5
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/pull/6295

:warning: Manually changed **director-v2** with: ``

**Comment by sanderegg** [comment]
# :warning: Additional manual hotfix: 1.76.6
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/pull/6345

:warning: Manually changed **clusters-keeper** _CLUSTERS_KEEPER_COMPUTATIONAL_BACKEND_DOCKER_IMAGE_TAG_ variable to point to 1.76.6
