### ISSUE TITLE
Unify version and distribution info across all services

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#6195]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Planned changes

All services include `_meta` to incorporate some metadata con the services distribution (e.g. version, etc)

The source of truth is going to be [`packaging.version.Version`](https://packaging.pypa.io/en/stable/version.html) We found that e.g. versions `1.0.0.a1`  was failing to be parsed with our regex while `packaging.version.Version` could parse it.  We found this issue in https://github.com/ITISFoundation/osparc-simcore/pull/6175 and partially resolved it.

- What about using [packaging.version.VERSION_PATTERN](https://packaging.pypa.io/en/stable/version.html#packaging.version.VERSION_PATTERN) as regex or even better `Version._regex`?
- How does this affect to our service versioning? e.g. front end will not understand `pre-release` and `meta` segments

```[tasklist]
### Tasks
- [ ] Unify definition of Version string 
- [ ] Unify `_meta` packages across all services
```
