### ISSUE TITLE
Optimization and wrap-up of catalog services web-api

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#6201]
The new implementation has some issues with speed and the service history does not scale well. It depends on the amount of services a user has access to more or less services. Therefore, depending on the user, the calls to pages might time out.

### Tasks
- [x] Speedup retrieving history and make it scalable
- [x] #6189
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/6099
- [ ] registry/director error handling: data guarantees and caching
- [x] batchGet services entrypoint
- [ ] Services collection order_by, filter
- [ ] registry: client for docker registry (optional)
- [ ] Background task: upgrade and add i/o in database?
- [x] Increase coverage catalog to 100
- [ ] FIX: implement transaction context for database. See new base_repo and context transactions!
- [x] https://github.com/ITISFoundation/osparc-simcore/issues/1854
- 

### Speedup retrieving history and make it scalable
- [x] create OAS to satisfy front-end needs. @odeimaiz needs answers to
    1) Can I access all the service:keys in my study
    2) Is the Study empty
    3) Is there any service:key in my study that: (in the following order)
      - it's retired
      - it's deprecated
      - can be updated

**Comment by pcrespov** [comment]
- [ ] should not rely on image label for service? https://github.com/itisfoundation/osparc-simcore/blob/534139a65bfe84ad909884030341237f7ed73ed3/services/catalog/src/simcore_service_catalog/api/rest/_services_resources.py#L245

**Comment by pcrespov** [comment]
catalog evolved
