### ISSUE TITLE
🚀 Release v<1.77.0>

### ISSUE THREAD

**Issue by YuryHrytsuk** [ITISFoundation/osparc-simcore#6212]
### Release version

1.77.0

### Commit SHA

TBD

### Previous pre-release

https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_<sprint_name><version>

### Planned date

TBD

### Did the commit CI suceeded?

- [X] The commit CI succeeded.

### Motivation

Regular sprint release

### Devops check 👷

- [ ] [Postgres backup s3 bucket](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/793)

### Summary 📝

- [ ] Prepare release link
```cmd
make release-prod version=<M.m.0>  git_sha=<commit_sha>
```
- [ ] Draft [release changelog](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Announce maintenance ( ** ANNOUNCE AT LEAST 24 HOURS BEFORE ** )
- redis add an entry in db `scheduled_maintenance` with key `maintenance` ``{"start": "2023-03-06T13:00:00.000Z", "end": "2023-03-06T15:00:00.000Z", "reason": "Release <vX.X.0>"}``. Note the time is in UTC, please adjust accordingly
    - [ ] aws
    - [ ] dalco
    - [ ] tip
- status page (https://manage.statuspage.io/)
    - [ ] osparc
    - [ ] s4l
- mattermost channels
    - [ ] maintenance
    - [ ] power users

### Releasing 🚀

- [ ] Maintenance page up.
```cmd
cd /deployment/production/osparc-ops-environments
make up-maintenance
make down-maintenance
```
- [ ] Release by publishing [draft](https://github.com/ITISFoundation/osparc-simcore/releases)
- [ ] Check release CI
- [ ] Check hanging sidecars. Helper command to run in director-v2 CLI `simcore-service-director-v2 close-and-save-service <uuid>`
- [ ] Check deployed
  - [ ] aws deploy
  - [ ] dalco deploy
  - [ ] tip deploy
- [ ] Check testing endpoint ex. `https://testing.osparc.speag.com/`
- [ ] Delete announcement
- [ ] Check e2e runs
- [ ] Announce
``` md
:tada: https://github.com/ITISFoundation/osparc-simcore/releases/tag/v<M.m.0>
```

**Comment by matusdrobuliak66** [comment]
# :warning: TODO @GitHK @matusdrobuliak66 
Sim4life lite product requires vendor configuration for release notes!! before releasing to the production (webserver has to be restarted)

**Comment by mrnicegyu11** [comment]
# TODO

Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/821

**Comment by YuryHrytsuk** [comment]
> # TODO
> 
> Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/821

Please, use section `Devops 👷` in the description of the issue for this

@mrnicegyu11

**Comment by mrnicegyu11** [comment]
> > # TODO
> > Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/821
> 
> Please, use section `Devops 👷` in the description of the issue for this
> 
> @mrnicegyu11

As I am admin of the github-org, I can edit your initial post. But this is not a solution that works for everyone, or are all backend contributors admin? What if Andrei has something to add?

**Comment by mrnicegyu11** [comment]
> > > > # TODO
> > > > Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/821
> > > 
> > > 
> > > Please, use section `Devops 👷` in the description of the issue for this
> > > @mrnicegyu11
> > 
> > 
> > As I am admin of the github-org, I can edit your initial post. But this is not a solution that works for everyone, or are all backend contributors admin? What if Andrei has something to add?
> 
> is it admin-only functionality? I can also edit the original post.

I am sure you can edit your own post, but to the best of my knowledge it is admin-functionality. Maybe a non-admin (andrei, odei) can try to edit it, i dont think it would work

**Comment by YuryHrytsuk** [comment]
> > > > > # TODO
> > > > > Merge https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/merge_requests/821
> > > > 
> > > > 
> > > > Please, use section `Devops 👷` in the description of the issue for this
> > > > @mrnicegyu11
> > > 
> > > 
> > > As I am admin of the github-org, I can edit your initial post. But this is not a solution that works for everyone, or are all backend contributors admin? What if Andrei has something to add?
> > 
> > 
> > is it admin-only functionality? I can also edit the original post.
> 
> I am sure you can edit your own post, but to the best of my knowledge it is admin-functionality. Maybe a non-admin (andrei, odei) can try to edit it, i dont think it would work

We just did a test with @odeimaiz  and @GitHK. They both can edit issue.

**Comment by matusdrobuliak66** [comment]
## :warning: TODO Matus
- setup `WEBSERVER_FOLDERS`=1

**Comment by YuryHrytsuk** [comment]
AWS TIP release issues:
- [X] lite product maintenance page is missing
- [ ] Traefik middleware are out-of-date (docker --> swarm)

**Comment by YuryHrytsuk** [comment]
@matusdrobuliak66 modify database

Add invitation_form: true in products.vendor column of the database. e.g.

```json
{
    "url": "https://acme.com",
    "license_url": "https://acme.com/license",
    "invitation_form": true,
    "name": "ACME",
    "copyright": "© ACME correcaminos",
    "has_landing_page": false
}
```

Source: https://github.com/ITISFoundation/osparc-simcore/pull/6217

**Comment by mrnicegyu11** [comment]
# IMPORTANT tip.science
ANE sets `PROJECTS_INACTIVITY_INTERVAL=14400 ` as requested by @Konohana0608

**Comment by YuryHrytsuk** [comment]
### Issue during release
- [X] Validate Simcore 1 Failed (Shall we have this as a CI test in ./osparc-config)?

**Comment by matusdrobuliak66** [comment]
# :warning:  Additional manual hotfix: 1.77.3
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/commit/cd8a2b8e95048d2ec62843679c9ac8cdba797ebe

:warning: Manually changed **static-webserver** with: `` image :warning:

**Comment by matusdrobuliak66** [comment]
# :warning:  Additional manual hotfix: 
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/commit/f4e1ec5ea34fbbc86b562797a5a8981d03c56d6c

:warning: Manually changed **static-webserver** with: `` image :warning:

**Comment by matusdrobuliak66** [comment]
# :warning:  Additional manual hotfix: v1.77.4 (In Progress)
- Cherry pick: https://github.com/ITISFoundation/osparc-simcore/commit/28c8ee584160ff3cc1502c0470c9ae88b1d1594e
- Cherry pick: one more to come

:warning: Manually changed **static-webserver** with: `` image :warning: 
:warning: Manually changed **garbage-collector** with: `` image :warning:

**Comment by pcrespov** [comment]
this release is a total [kugelblitz](https://en.wikipedia.org/wiki/Kugelblitz_(astrophysics)) 🔥🔥🔥 fix! :-)

**Comment by matusdrobuliak66** [comment]
# :warning: 
in `tip.science` manually restarted webserver with `PROJECTS_MAX_NUM_RUNNING_DYNAMIC_NODES` = 6

**Comment by matusdrobuliak66** [comment]
# :warning: Manual change of ENV var
in `tip.science` & `sim4life.io` manually restarted autoscaling service: https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/commit/f1f8f49b5a3588978fa99af560b23d240994cd77

**Comment by matusdrobuliak66** [comment]
# :warning: Manually adding ENV var to director-v2
- because of timeout issue in `osparc.io` and `sim4life.io` we have added manually this env var `DYNAMIC_SIDECAR_API_SAVE_RESTORE_STATE_TIMEOUT` to director-v2
