### ISSUE TITLE
Beta Users

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-simcore#640]
Beta Users will be invited to 'play' with osparc and provide feedback. initially, this will be clancy, horn, novelli, and rajwa. we need to make sure that their experience is acceptable. 

we should be collecting here, what is needed for that:
- [x] persistence (users that setup a project should be able to save it and get back to it)
- [ ] permissions (users should only see their own projects, or the ones that have been shared with them / that they have been given access too)
- [x] access through a suitable platform version on the dalco cluster
- [x] users can register by invitation only

to be extended...
