### ISSUE TITLE
Improve statistics for RUT

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#6529]
To improve statistics retrieved from Resource usage tracker it would be nice to have the "submission" times:
- in computational services, that is when a pipeline is submited (**before it actually is really started**),
- in dynamic services, that is when a user starts a service (**before it actually is really started**)

These shall be sent to Resource usage tracker (RUT) service such that there is a trace of them.

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6528
- [ ] Dynamic Backend: send job submission message when user triggers service start
- [ ] Resource usage tracker: handle service submit message
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6530
```
