### ISSUE TITLE
Open telemetry exception raised because of type error

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-simcore#6938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Planned changes

Sometimes we see the following issue in Graylog:
```
log_level=ERROR | log_timestamp=2024-12-11 05:00:10,293 | log_source=opentelemetry.context:detach(154) | log_uid=None | log_oec=None| log_trace_id=d71b9949c21c98ff34df98494d746301 | log_span_id=b2f25cb4b82b7da3 | log_resource.service.name= | log_trace_sampled=True] | log_msg=Failed to detach context
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.11/site-packages/opentelemetry/context/__init__.py", line 152, in detach
    _RUNTIME_CONTEXT.detach(token)
  File "/home/scu/.venv/lib/python3.11/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach
    self._current_context.reset(token)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected an instance of Token, got {'current-span-b4992ee6-0846-47e8-89e2-8f2a69add41a': _Span(name="POST /v2/computations", context=SpanContext(trace_id=0xd71b9949c21c98ff34df98494d746301, span_id=0xb2f25cb4b82b7da3, trace_flags=0x01, trace_state=[], is_remote=False))}
```

```[tasklist]
### Todo
- [x] Ensure this is not "masking" an exception internal to the simcore repo
- [x] Get rid of error if possible.
```

**Comment by bisgaard-itis** [comment]
See also 
https://github.com/open-telemetry/opentelemetry-python/pull/4164
https://github.com/open-telemetry/opentelemetry-python/pull/4163
