### ISSUE TITLE
Migration of database structure and data

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#709]
When modifying what get saved and how in the database, we need some mechanism to update the database and its data (the data might have its own schemas)

- database models package: Every database has all its models (schemas) in one place, e.g. postgres service serves a database and its table schemas are in [packages/postgres_models](packages/postgres_models)
- Define a robust migration workflow :
   - on different deployed dbs?
   - revert back in case of failures or mafunction
   - clean version control 

#### TODOS
- [x] move all models to its own package. One package
- [x] add db migration
- [x] add entrypoint in db-models package
- [ ] move db data.  pg dumps to [docker volumes](https://docs.docker.com/v17.09/engine/admin/volumes/)
- [x] cleanup old ops scripts and document rationale
