### ISSUE TITLE
ISAN Result Visualizer Project

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-simcore#777]
have a project that 
- [x] gets predefined data from the portal or dat-core (might lead to login issues, as it has to work for the anonymous user - talk to blackfynn about the public data center)
- [x] displays it in a paraview viewer with predefined, but editable visualization (e.g., E-field stream lines in combination with slice field view)
- [x] display data in a rawgraph service with predefined visualization settings (e.g., some measurement data)

**Note**: predefined both what data is shown and how it is fetched.

**Comment by esraneufeld** [comment]
some comments from joost on slack:

[...] When people publish a dataset, what happens is that we copy the files to a public S3 bucket. The portal will have the S3 locations for all these files (and the files are static per version of a dataset)
I think this is what you’ll want to use.
[...]
This is what we are currently working on and hopefully have in place within next 3 weeks but I can probably figure out how to get you access earlier.
[...]
One thing I should mention. The public s3 bucket is that the bucket is a “requester pays” bucket so you would still need to have AWS credentials to get the data. Transfer costs will be billed to the user who requests the data. However, if you access the data from within AWS, there are no costs associated with this. (this is how we ensure sustainability and prevent the NIH for getting a very large invoice when the platform is successful)
One thing we could do is to setup a NIH account or something, or NIH user under one of our accounts
[...]
Given an DOI for a dataset, you will be able to request a manifest of the dataset and all the locations of the files in that dataset. [...]

**Comment by ignapas** [comment]
Missing:
* @esraneufeld provides input files
* @ignapas Rawgraph persistency
* Saving the state and data of dynamic services for templates (copy on write?)

**Comment by sanderegg** [comment]
In ISAN, the following use case was implemented:
- template consisting of a file-picker and a 3d-viewer with pre-defined data
