### ISSUE TITLE
Docker configs and customization of config files for different deployments

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#857]
The configuration of every service in the platform is centralized in a config file. This config is a yaml file defined by a schema and normally placed under ``src/{service-name}/config/*.yaml``. This configuration is loaded upon startup of the server and is accessible to every subsystem of the service. Up to know, we provided different variant of that file mostly to test different situations or when we deploy in development mode on our own host. Nonetheless, the configuration when services were deployed was **fixed**. E.g. the webserver services always uses [server-docker-prod.yaml](services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml) when is deployed. This file is shipped with the source code so sensitive information (e.g. passwords, etc) cannot be displayed. For that we use environment variables. Moreover, we also use the same approach to tune the differences between master/staging or production deploys. 
After some time, this approach has proven to be difficult to maintain: e.g. what entries in the config file should be parameterized with environ variables? All deploys need to updated every a new environ is added in the config-prod.yaml, etc 

A plausible solution would be if every deploy has its own config file. These files are stored in a separate devops repository. Passwords and other sensitive information might still be parameterized via environ variables but the rest can be customized for the needs of every deploy. Finally, every configuration saved in the devops repo MUST comply with the config schemas that are about to be deployed. This is a step that must be included in the deployment workflow to prevent errors upon service startup (remember that failures in the validation of the schema are fatal and stop the service)

A plausible solution to achieving customize config per deploy consists of incorporating [docker configs](https://docs.docker.com/engine/swarm/configs/) in our workflow. This way config file is passed to the service via the docker-compose which will place it inside the docker upon startup, e.g. 
```yaml
webserver:
    image: ${DOCKER_REGISTRY:-itisfoundation}/webserver:${DOCKER_IMAGE_TAG:-latest}
    build:
      context: ../
      dockerfile: services/web/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:cache
        - ${DOCKER_REGISTRY:-itisfoundation}/webserver:${DOCKER_IMAGE_TAG:-latest}
      target: production
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "https://github.com/ITISFoundation/osparc-simcore"
        org.label-schema.vcs-ref: "${VCS_REF}"
    configs:
      - source: webserver_config
        target: /home/scu/server-docker-prod.yaml
...
configs: 
  webserver_config:
    file: ./services/web/server/src/simcore_service_webserver/config/server-docker-prod.yaml
```

So some steps that I can imaging so far are:

- [ ] update [docker-compose](services/docker-compose.yml) and [docker-compose-devel](services/docker-compose.devel.yml) to include docker configs
- [ ] review environ variables. Keep those sensitive and set others to the config file (remember that we will have multiple of them)
- [ ] normalize naming of config files **for all** services (e.g. ``config-dev.yaml, config-prod.yaml, ...``). Please add e.g. in docs/ a file with conventions.
- [ ] review and remove unnecesary config files in osparc-simcore repo
- [ ] create custom config files for every service in each of the deploys: master, staging and production. These configs must be saved and versioned in the *devops repo* accessible to the deployment tools
- [ ] adjust deployment workflow [deployer agent/bot] to validate that current config will run with versions of the services being deployed (e.g. can be done validating configs against  schemas before passing them or simply starting a service and detecting whether validation failure occurred... in any case, service always validates config file against schema before starting)

**Comment by pcrespov** [comment]
obsolete
