### ISSUE TITLE
File Picker UX

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#861]
Bugs:
- [x] When the content of the tree changes (add/remove file) and the user presses reload, the directory affected appear n+1 times.
- [x] A UUID should not be the directory label. #531 
- [x] Blackfynn now supports nested subdirs. API calls need to be updated. #439 #531 
- [x] Extensions for files coming from DatCore are not shown.

Improvements:
- [x] Make visible when tree is being built. Spinner maybe.
- [ ] Show progress for uploading, copying, fetching data. #454 
- [x] Remove pie chart until there is real info to be displayed.
- [x] Show at least the empty s3.simcore directory when there are no files associated to the user.
- [x] Make selected file entry more attractive. (white bar)
- [x] Rearrange buttons
- [x] Show real file sizes
